/*
 * Copyright (C) 2023 Shinacho
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fuzzyworld;

import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import kinugasa.game.I18N;
import kinugasa.game.ui.Dialog;
import kinugasa.game.ui.DialogIcon;
import kinugasa.game.ui.DialogOption;
import kinugasa.resource.db.DBConnection;
import kinugasa.resource.db.KResultSet;

/**
 *
 * @author Shinacho
 */
public class SaveDataManageForm extends javax.swing.JFrame {

	/**
	 * Creates new form SaveDataManageForm
	 */
	public SaveDataManageForm() {
		initComponents();
		init();
	}
	private static final SaveDataManageForm INSTANCE = new SaveDataManageForm();

	public static SaveDataManageForm getInstance() {
		return INSTANCE;
	}

	private void init() {
		setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());

		Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
		center.x -= getWidth() / 2;
		center.y -= getHeight() / 2;
		setLocation(center);

		for (int i = 0; i < Const.Save.SAVE_DATA_NUM; i++) {
			int n = i + 1;
			String fileName = "resource/data/data" + n + ".mv.db";
			if (n == 1) {
				DBConnection.getInstance().open("file:./resource/data/data" + n, "sa", "adm");
				KResultSet rs1 = DBConnection
						.getInstance()
						.execDirect("select q.TITLE, q.DESC from S_CurrentQuest c left join Quest q on c.QuestID=q.QuestID where c.Questid = 'main'");
				if (rs1.isEmpty()) {
					jTextArea1.setText(I18N.get("新規"));
				} else {
					String title = rs1.row(0).get(0).get();
					String desc = rs1.row(0).get(1).get();
					jTextArea1.setText(title + "\n" + desc);
				}
				DBConnection.getInstance().close();
			}
			jComboBox1.addItem(fileName);
			jComboBox2.addItem(fileName);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FUZZY WORLD");

        jLabel1.setText("SAVE DATA MANAGER");

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("COPY TO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		String from = jComboBox1.getSelectedItem().toString();
		String to = jComboBox2.getSelectedItem().toString();

		String fileNameFrom = from.substring(from.lastIndexOf("/"));
		String fileNameTo = to.substring(to.lastIndexOf("/"));

		File f = new File("resource/data/" + fileNameFrom);
		File t = new File("resource/data/" + fileNameTo);

		if (fileNameFrom.equals(fileNameTo)) {
			Dialog.info(I18N.get("コピー前とコピー後が同じです"));
			return;
		}
		if (Dialog.yesOrNo("FUZZY WORLD", DialogIcon.QUESTION, I18N.get("本当にコピーする")) == DialogOption.YES) {
			t.delete();
			try {
				Files.copy(f.toPath(), t.toPath(), StandardCopyOption.REPLACE_EXISTING);
			} catch (IOException ex) {
			}
			Dialog.info(I18N.get("コピー完了"));
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		String from = jComboBox1.getSelectedItem().toString();
		String fileNameFrom = from.substring(from.lastIndexOf("/"));
		File f = new File("resource/data/" + fileNameFrom);

		if (Dialog.yesOrNo("FUZZY WORLD", DialogIcon.QUESTION, fileNameFrom + "\n" + I18N.get("を本当に消す")) == DialogOption.YES) {
			try {
				f.delete();
				//初期化処理
				f.createNewFile();
				DBConnection.getInstance().open("file:./resource/data/" + fileNameFrom.replaceAll(".mv.db", ""), "sa", "adm");
				//Sound
				DBConnection.getInstance().execByFile("resource/data/sql/insertSound.sql");
				DBConnection.getInstance().execByFile("resource/data/sql/createTable.sql");
				//初期データ投入
				DBConnection.getInstance().execByFile("resource/data/sql/readData.sql");
				DBConnection.getInstance().close();

				Dialog.info(fileNameFrom + "\n" + I18N.get("削除完了"));
				updateQuest();
			} catch (IOException ex) {
			}
		}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		updateQuest();
    }//GEN-LAST:event_jComboBox1ActionPerformed

	private void updateQuest() {
		String from = jComboBox1.getSelectedItem().toString();
		String fileNameFrom = from.substring(from.lastIndexOf("/"));
		File f = new File("resource/data/" + fileNameFrom);

		DBConnection.getInstance().open("file:./resource/data/" + fileNameFrom.replaceAll(".mv.db", ""), "sa", "adm");
		KResultSet rs1 = DBConnection
				.getInstance()
				.execDirect("select q.TITLE, q.DESC from S_CurrentQuest c left join Quest q on c.QuestID=q.QuestID where c.Questid = 'main'");
		if (rs1.isEmpty()) {
			jTextArea1.setText(I18N.get("新規"));
		} else {
			String title = rs1.row(0).get(0).get();
			String desc = rs1.row(0).get(1).get();
			jTextArea1.setText(title + "\n" + desc);
		}
		DBConnection.getInstance().close();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SaveDataManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SaveDataManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SaveDataManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SaveDataManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SaveDataManageForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
